from numerical_analysis.systems_of_equations.equations_system import EquationsSystems
from numerical_analysis.systems_of_equations.linear_systems import GaussSeidel, Jacobi, SOR
from numerical_analysis.systems_of_equations.nonlinear_systems import Newtons